package co.edu.uniquindio.clinica.enums;

public enum Servicios {
    ODONTOLOGIA, PEDIATRIA, GENERAL, ANESTESIOLOGIA, GINECOLOGIA, NEUMOLOGIA,
    OBSTETRICIA, ALERGOLOGIA, CARDIOLOGIA, ONCOLOGIA, PSIQUIATRIA, DERMATOLOGIA
}
